apiVersion: batch/v1
kind: Job
metadata:
  name: whale-say-job
spec:
  template:
    metadata:
      labels:
        job-type: whale #<.>
    spec:
      containers:
      - name: whale-say-container
        image: docker/whalesay
        command: ["cowsay","Hello DevNation"]
      restartPolicy: Never