apiVersion: batch/v1
kind: CronJob
metadata:
  name: whale-say-cronjob
spec:
  schedule: "*/1 * * * *" #<.>
  jobTemplate:                   
    spec:                        
      template:    
        metadata:
          labels:
            job-type: whale #<.>              
        spec:
          containers:
          - name: whale-say-container
            image: docker/whalesay
            command: ["cowsay","Hello DevNation"]
          restartPolicy: Never